name: CI Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew detekt koverXmlReport sonar

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Semantic Release Prepare
        uses: codfish/semantic-release-action@v3
        with:
          plugins: |
            ['@semantic-release/commit-analyzer']
          dry-run: true
        id: semantic-prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew clean assemble publish -Pversion=${{ steps.semantic-prepare.outputs.release-version }} --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PWD }}

      - name: Semantic Release
        uses: codfish/semantic-release-action@v3
        with:
          additional-packages: |
            ['@semantic-release/github', '@semantic-release/exec']
          plugins: |
            [
              '@semantic-release/commit-analyzer', 
              '@semantic-release/release-notes-generator', 
              '@semantic-release/github'
            ]
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

